# Generated by Django 4.0.6 on 2022-07-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_users_groups_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groups',
            table='[bot].[groups]',
        ),
    ]
