# Generated by Django 4.0.6 on 2022-07-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_groups_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groups',
            table='[bot].[bot_groups]',
        ),
    ]
