# Generated by Django 4.0.6 on 2022-07-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='[bot].[bot_user_in_groups]', to='bot.groups'),
        ),
    ]
