# Generated by Django 4.0.6 on 2022-07-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_groups_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='groups',
            new_name='link_role',
        ),
    ]
