# Generated by Django 4.0.6 on 2022-07-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_rename_link_role_groups_link_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
