# Generated by Django 4.0.6 on 2022-07-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_staff_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
